apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
        - name: django-app-container
          image: your-django-image:tag
          ports:
            - containerPort: 8000
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: "your_project.settings"  # Replace with your actual project settings module
            - name: DEBUG
              value: "False"  # Set to "True" during development, "False" for production
            - name: SECRET_KEY
              value: "your_secret_key"  # Replace with a secure secret key
            - name: ALLOWED_HOSTS
              value: "*"  # Adjust based on your domain or IP address
