version: '3.6'
services:
  frontend:
    restart: always
    command : npm start
    container_name: front
    build: ./frontend/my-banking-app-frontend/
    image: reactjs-app:k1 
    ports:
      - "3000:3000"
  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
  backend:
    build:  ./backend/banking-rest-api-develop-using-python-django/banksystem/
    image: python-app:k1
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    links:
      - mongodb
    depends_on:
      - migration
  
  migration:
    build: ./backend/banking-rest-api-develop-using-python-django/banksystem/
    image: app
    command: python manage.py migrate
    links:
      - mongodb
    depends_on:
      - make_migrations

  make_migrations:
    build: ./backend/banking-rest-api-develop-using-python-django/banksystem/
    image: app
    command: python manage.py makemigrations
    links:
      - mongodb
    depends_on:
      - mongodb